<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>Search acl</h1>
    <p><?php echo $this->tag->linkTo(["acl/new", "Create acl"]) ?></p>
</div>

<?php echo $this->getContent() ?>

<?php echo $this->flash->output() ?>

<form action="acl/search" class="form-horizontal" method="get">
    <div class="form-group">
    <label for="fieldId" class="col-sm-2 control-label">Id</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id", "type" => "number", "class" => "form-control", "id" => "fieldId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldRoleId" class="col-sm-2 control-label">Role</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["role_id", "type" => "number", "class" => "form-control", "id" => "fieldRoleId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldActionId" class="col-sm-2 control-label">Action</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["action_id", "type" => "number", "class" => "form-control", "id" => "fieldActionId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldResourceId" class="col-sm-2 control-label">Resource</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["resource_id", "type" => "number", "class" => "form-control", "id" => "fieldResourceId"]) ?>
    </div>
</div>


    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
        </div>
    </div>
</form>
