<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["acl", "Go Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Create acl</h1>
</div>

<?php echo $this->getContent(); ?>

<form action="acl/create" class="form-horizontal" method="post">
    <div class="form-group">
    <label for="fieldRoleId" class="col-sm-2 control-label">Role</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["role_id", "type" => "number", "class" => "form-control", "id" => "fieldRoleId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldActionId" class="col-sm-2 control-label">Action</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["action_id", "type" => "number", "class" => "form-control", "id" => "fieldActionId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldResourceId" class="col-sm-2 control-label">Resource</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["resource_id", "type" => "number", "class" => "form-control", "id" => "fieldResourceId"]) ?>
    </div>
</div>


    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
        </div>
    </div>
</form>
