<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["users", "Go Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Create users</h1>
</div>

<?php echo $this->getContent(); ?>

<form action="/users/create" class="form-horizontal" method="post">
    <div class="form-group">
    <label for="fieldPassword" class="col-sm-2 control-label">Password</label>
    <div class="col-sm-10">
        <?php echo $this->tag->passwordField(["password", "size" => 30, "class" => "form-control", "id" => "fieldPassword"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["name", "size" => 30, "class" => "form-control", "id" => "fieldName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEmail" class="col-sm-2 control-label">Email</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["email", "size" => 30, "class" => "form-control", "id" => "fieldEmail"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldRole" class="col-sm-2 control-label">Role</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["role", "size" => 30, "class" => "form-control", "id" => "fieldRole"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldValidationkey" class="col-sm-2 control-label">Validationkey</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["validationkey", "size" => 30, "class" => "form-control", "id" => "fieldValidationkey"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldStatus" class="col-sm-2 control-label">Status</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["status", "size" => 30, "class" => "form-control", "id" => "fieldStatus"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCreatedat" class="col-sm-2 control-label">Createdat</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["createdat", "size" => 30, "class" => "form-control", "id" => "fieldCreatedat"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUpdatedat" class="col-sm-2 control-label">Updatedat</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["updatedat", "size" => 30, "class" => "form-control", "id" => "fieldUpdatedat"]) ?>
    </div>
</div>


    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
        </div>
    </div>
</form>
